export const Types = {
    RENDER: 'RENDER',
    GET_DATA: 'GET_DATA',
    SET_DATA: 'SET_DATA',
    DELETE_ITEM: 'DELETE_ITEM',
    UPDATE_DATA: 'UPDATE_DATA',
    UPDATE_COMMENT: 'UPDATE_COMMENT',
    SET_ID: 'SET_ID',
    EDIT_REPLIE: 'EDIT_REPLIE',
    DELETE_REPlY: 'DELETE_REPlY',
    DELETE_ID: 'DELETE_ID',
}